### ISSUE TITLE
PerformanceObserver should not throw when entryTypes is empty

### ISSUE THREAD

**Issue by victor-homyakov** [fastly/performance-observer-polyfill#7] opened 2020-01-16 08:46 UTC
Right now polyfill throws an error when there is no valid entry types in a call to `observe()`: https://github.com/fastly/performance-observer-polyfill/blob/master/src/observer.ts#L12

The latest spec version does not say anymore that observer should throw an error - rather it should issue a console warning

> Remove all types from entry types that are not contained in relevantGlobal's frozen array of supported entry types. The user agent SHOULD notify developers if entry types is modified. For example, a console warning listing removed types might be appropriate.
If the resulting entry types sequence is an empty sequence, abort these steps. The user agent SHOULD notify developers when the steps are aborted to notify that registration has been aborted. For example, a console warning might be appropriate.

https://w3c.github.io/performance-timeline/#observe-method

Explanation why it shouldn't throw is given in https://github.com/w3c/performance-timeline/issues/87.

Also, latest web platform tests could work as a reference: https://github.com/web-platform-tests/wpt/blob/master/performance-timeline/po-observe.any.js#L24-L35

**Comment by crellison** [comment] 2020-04-15 23:15
@phamann Any updates on this? It's been three months and this library is still not spec compliant. Does this package need more maintainers?

**Comment by phamann** [comment] 2020-04-16 09:36
Hey @victor-homyakov, @crellison thank you for raising this issue and apologies for the extremely delayed response and fix.  

I've attempted to fix this issue and comply with other spec changes related to `observe()` in #10 please review and let me know your thoughts on the implementation and i'll try and get it merged and cut a new release ASAP. 

> Does this package need more maintainers?

@crellison we are always happy to accept further issues or pull requests with any contributions you see fit.

**Comment by crellison** [comment] 2020-04-16 16:46
Thanks for updating @phamann 
My question about maintainers was basically a "should I fix it" question. If the spec gets updated again, I'm happy to help update the polyfill though.

Out of curiosity, does fastly automatically ship this with some document/asset requests it services? Maybe it started doing that six days ago? Just asking because I tracked down this polyfill by the error string following an unexpected console error I saw.

**Comment by phamann** [comment] 2020-04-20 10:39
> Out of curiosity, does fastly automatically ship this with some document/asset requests it services

@crellison No we don't (and never would) automatically ship this or rewrite any responses at Fastly. We do however include this library in [insights.js](https://insights.fastlylabs.com/) which is an opt-in RUM service which some Fastly customers deploy to their sites. 

> Maybe it started doing that six days ago? Just asking because I tracked down this polyfill by the error string following an unexpected console error I saw.

As this library is included in the above script and is also used by many people as an open-source polyfill. It's hard for me to determine where and why you may have seen this. If you could share more details to reproduce that would be great. Even just t help me reach out to the users to let them know it is happening and we have a new fix to prevent it. Feel free to email me if you don't want to share publicly.

**Closed** 2020-04-20 11:53 UTC
